dotadb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

#from esports.views import index
from django.views.generic import TemplateView

from .views import list
from .views import index

app_name='dotadb'
urlpatterns = [
    url(r'^$'     , index, name="index"),
    url(r'^list/$', list, name="list")
]

esports/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

from django.conf.urls.static import static

#from esports.views import index
from django.views.generic import TemplateView
from django.conf import settings
app_name = 'esports'
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$'     , TemplateView.as_view(template_name='index.html'), name="index"),
    url(r'^dota/', include('dotadb.urls', namespace='dotadb'))
] 

dotadb/models.py
from django.db import models

# Create your models here.


class Player(models.Model):
    first_name = models.CharField(max_length = 50)
    user_name  = models.CharField(max_length = 50)
    last_name  = models.CharField(max_length = 50)


class LobbyMatch(models.Model):
    date_occured = models.DateField()
    players = models.ManyToManyField(Player)


class Replay(models.Model):
    replayfile = models.FileField(upload_to='replays/%Y_%m_%d')

dotadb/forms.py
from django import forms

class ReplayForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField(
            label='Select a file',
            help_text='Dota 2 Replay'
        )

dotadb/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext

from django.http import HttpResponseRedirect
from .forms import ReplayForm

from .models import Replay
from .forms import ReplayForm

# Create your views here.

def index(request):
    if request.method == 'POST':
        form = ReplayForm(request.POST, request.FILES)
        if form.is_valid():
            replay = Replay(replayfile=request.FILES['files'])
            replay.save()
            return HttpResponseRedirect(reverse('dotadb.views.index'))
    else:
        form = ReplayForm()

    replays = Replay.objects.all()
    return render(request, 'dotadb/index.html', {'replays' : replays, 'form' : form})



def list(request):
    replays = Replay.objects.all()
    return render(request,'dotadb/list.html', {'replays': replays})



def handle_replay(replay):
    with open('filename', 'wb+') as destination:
        for chunk in f.chunks() :
            destination.write(chunk)

esports/views.py
from django.shortcuts import render


#def index(request):
#    return render(request, 'index.html')

dotadb/templates/dotadb/index.html
{% extends "base.html" %}


{% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'dotadb/index.css' %}" />

{% endblock style %}

{% block content %}
<div class="row-fluid no-gutters text-center" id="background">
    <!-- center -->
    <form action="{% url 'index'  %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p> {{form.file}} </p>
        <input type="submit" value="Upload" name="file" id="file" name="replay" class="inputfile">
        <label for="file">upload</label>
        <!-- button -->
    </form>

    {% if replays %}
        <ul>
        {% for replay in replays %}
            <li><a href="{{ replay.replayfile.url }}">{{ replay.replayfile.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No documents found.</p>
    {% endif %}
</div>

{% endblock content %}

dotadb/templates/dotadb/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Minimal Django File Upload Example</title>   
    </head>
    <body>
    <!-- List of uploaded documents -->
    {% if replays %}
        <ul>
        {% for replay in replays %}
            <li><a href="{{ replay.replayfile.url }}">{{ replay.replayfile.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No documents found.</p>
    {% endif %}

       
    </body>
</html> 

esports/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %} Madison E-sports {% endblock title %}</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" id="bootstrap-css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


        <!-- fonts in use -->
        <link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

        <link href="https://fonts.googleapis.com/css?family=Krona+One" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">

        <link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet">


        
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'base.css'%}">
        {% block style %} {% endblock style %}
    </head>
    <body>
        <div class = "container-fluid" id="shadow">
            <nav class="navbar navbar-default navbar-fixed-top" data-spy="affix" id="navbar">
                
                    <a class = "navbar-brand" href="{% url 'index' %}" id="brand">Madison E-sports</a>
                    <div class = "collapse navbar-collapse">
                        <a class = "btn button-nav navbar-btn" href="{% url 'dotadb:index'%}">Dota 2</a>
                        <a class = "btn button-nav navbar-btn" >League</a>
                        <a class = "btn button-nav navbar-btn" >Overwatch</a>
                        <a class = "btn button-nav navbar-btn" >CS:GO</a>
                        <a class = "btn button-nav navbar-btn" >Hearthstone</a>
                        <a class = "btn button-nav navbar-btn" >PUBG </a>
                    </div>
            </nav>
        </div>
        <div class = "container-fluid" id="content">
            {% block content %}{% endblock content%}      
        </div>        
    </body>
</html>

esports/templates/index.html
{% extends "base.html" %}


{% block style %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}" />

{% endblock style %}

{% block content %}
    <div class="row no-gutters text-center" id="background">
        <img src="{% static 'esports-transparent-new.png' %}" id="logo">
        </img>

    </div>
    <div class="row no-gutters" id="transition">
    </div>
    <div class="row no-gutters" id="about">
        <div class = "col-md-4 col-md-offset-1" id="margin">
            <h1 class = "display-2">Our club</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a tortor vel elit molestie ultricies a maximus felis. Morbi quis nisi non erat sodales rhoncus in ut ex. Nulla ornare nulla ipsum, nec euismod est pellentesque quis. Vestibulum nec elementum diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas vel dictum arcu, quis placerat ipsum. Duis elementum accumsan quam, sed rhoncus tortor tincidunt vitae. Cras volutpat ut nulla at imperdiet. Etiam semper gravida libero, et pharetra magna imperdiet nec. Quisque egestas libero non iaculis ultricies.<br>

                Curabitur bibendum, sem pharetra tincidunt bibendum, dolor risus hendrerit odio, in laoreet dolor dui ac mauris. Morbi et tincidunt eros. In non mi mi. Vivamus bibendum ullamcorper velit et interdum. Morbi lacus nisi, hendrerit vel felis non, imperdiet volutpat augue. Nullam luctus dignissim nisl, pharetra interdum enim pretium non. Nunc odio mauris, auctor sit amet mi vitae, vestibulum molestie lacus. Ut orci nibh, tempor vitae luctus eget, pharetra eget metus. In fringilla tincidunt purus vitae semper. Suspendisse sit amet eros euismod, porttitor risus et, vestibulum tellus.
            </p>
        </div>
    </div>
    <div class="row no-gutters" id="about">
        <div class="col-md-4 col-md-offset-7">
            <h1 class = "display-2"> Join us!</h1>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a tortor vel elit molestie ultricies a maximus felis. Morbi quis nisi non erat sodales rhoncus in ut ex. Nulla ornare nulla ipsum, nec euismod est pellentesque quis. Vestibulum nec elementum diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas vel dictum arcu, quis placerat ipsum. Duis elementum accumsan quam, sed rhoncus tortor tincidunt vitae. Cras volutpat ut nulla at imperdiet. Etiam semper gravida libero, et pharetra magna imperdiet nec. Quisque egestas libero non iaculis ultricies.<br>

                Curabitur bibendum, sem pharetra tincidunt bibendum, dolor risus hendrerit odio, in laoreet dolor dui ac mauris. Morbi et tincidunt eros. In non mi mi. Vivamus bibendum ullamcorper velit et interdum. Morbi lacus nisi, hendrerit vel felis non, imperdiet volutpat augue. Nullam luctus dignissim nisl, pharetra interdum enim pretium non. Nunc odio mauris, auctor sit amet mi vitae, vestibulum molestie lacus. Ut orci nibh, tempor vitae luctus eget, pharetra eget metus. In fringilla tincidunt purus vitae semper. Suspendisse sit amet eros euismod, porttitor risus et, vestibulum tellus.
        </div>
    </div>
{% endblock content %}